[project]
name = "complexity-17"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "nevergrad>=1.0.12",
    "numpy>=2.4.1",
    "pyqt6>=6.10.2",
    "torch>=2.9.1",
]
